@isTest
private class ParkLocatorTest {
    @isTest static void testCountry(){
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new ParkServiceMock());
        // Call the method that invokes a callout
       	List<string> lstparks = ParkLocator.country('India');
        // Verify that a fake result is returned
        System.assertEquals(3, lstparks.size()); 
    }
}